import type { Metadata } from 'next';
import LegalPageLayout from '@/components/site/LegalPageLayout';

export const metadata: Metadata = {
  title: 'Terms of Service | MiroFish',
  description: 'Terms of Service for using the MiroFish website and prediction platform.',
};

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout
      eyebrow="Terms"
      title="Terms of Service"
      description="These terms govern access to and use of the MiroFish website, products, and related services."
    >
      <div className="space-y-8 text-sm sm:text-base leading-7 text-muted">
        <section className="space-y-3">
          <p><strong className="text-text">Effective date:</strong> April 11, 2026</p>
          <p>
            By accessing or using MiroFish, you agree to these Terms of Service. If you do not agree, do not use the service.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Use of the service</h2>
          <p>
            MiroFish provides AI-assisted scenario analysis, simulation, and reporting tools. You agree to use the service
            only for lawful purposes and in a way that does not interfere with the security, availability, or operation of the platform.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and for activity conducted
            through your account. We may suspend or terminate accounts that violate these terms or threaten the platform or other users.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Payments and subscriptions</h2>
          <p>
            Certain features may require payment, credits, or a subscription. Prices, credit packages, and plan details may
            change over time. Unless otherwise stated, fees are non-refundable except where required by law.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">User content</h2>
          <p>
            You retain responsibility for prompts, uploads, and other content you submit. You represent that you have the
            rights needed to submit that content and that it does not violate the law or third-party rights.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">No professional advice</h2>
          <p>
            Outputs generated by MiroFish are for informational purposes only and do not constitute legal, financial,
            investment, medical, or other professional advice. You are responsible for evaluating results before relying on them.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Intellectual property</h2>
          <p>
            The MiroFish website, branding, software, and related materials are protected by applicable intellectual property laws.
            Except as permitted by law or written permission, you may not copy, resell, reverse engineer, or exploit the service in an unauthorized way.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Disclaimers and limitation of liability</h2>
          <p>
            The service is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind. To the fullest extent
            permitted by law, MiroFish is not liable for indirect, incidental, special, consequential, or punitive damages,
            or for loss of data, revenue, profits, or business opportunities arising from use of the service.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Changes</h2>
          <p>
            We may update these Terms of Service from time to time. Continued use of the service after changes become effective
            constitutes acceptance of the updated terms.
          </p>
        </section>
        <section className="space-y-3">
          <h2 className="font-display font-700 text-2xl text-bright">Contact</h2>
          <p>
            Questions about these terms can be sent to <a className="text-mint hover:text-mint-dim" href="mailto:support@mirofish.us">support@mirofish.us</a>.
          </p>
        </section>
      </div>
    </LegalPageLayout>
  );
}
